### ISSUE TITLE
not works in CentOS7

### ISSUE THREAD

**Issue by merlokk** [gpakosz/whereami#15]
for CentOS it needs to add `_BSD_SOURCE` define to make it works

https://github.com/Proxmark/proxmark3/issues/685

**Comment by gpakosz** [comment]
Well...

I'm not sure how to address this as [my own build properly shows how to make it work by defining `-D_XOPEN_SOURCE=500`](https://github.com/gpakosz/whereami/blob/master/_gnu-make/Makefile#L51-L55).

It seems to me doing `#define _XOPEN_SOURCE 500` inside `whereami.c` is pretty moot because:

- this would mean writing
  ```
  #undef _XOPEN_SOURCE
  #define _XOPEN_SOURCE 500
  #include <stdlib.h>
  ```
  the `#undef` bits being needed in case `_XOPEN_SOURCE` is already defined by the build system

- even when defining `_XOPEN_SOURCE` myself, I don't think this would be robust in case `whereami.c` is included from another `.c` file (instead of being part of the build) and `stdlib.h` has already been included

**Comment by gpakosz** [comment]
For the record, `-D_XOPEN_SOURCE=500` works as intended in CentOS 7.5.1804 and is also what it takes to have `realpath()` on other Linux distributions

```
$ cd /tmp
$ git clone https://github.com/gpakosz/whereami.git
```
```
$ vagrant init centos/7
$ vagrant up
$ vagrant ssh
```
```
[vagrant@localhost vagrant]$ uname -a
Linux localhost.localdomain 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
[vagrant@localhost vagrant]$ cd /vagrant
[vagrant@localhost vagrant]$ sudo yum -y groupinstall "Development Tools"
[vagrant@localhost vagrant]$ make -j -C _gnu-make

[vagrant@localhost vagrant]$ ./bin/linux-x86_64/executable --load-library=./bin/linux-x86_64/library.so
executable path: /vagrant/bin/linux-x86_64/executable
  dirname: /vagrant/bin/linux-x86_64
  basename: executable
module path: /vagrant/bin/linux-x86_64/executable
  dirname: /vagrant/bin/linux-x86_64
  basename: executable

library loaded
executable path: /vagrant/bin/linux-x86_64/executable
  dirname: /vagrant/bin/linux-x86_64
  basename: executable
module path: /vagrant/bin/linux-x86_64/library.so
  dirname: /vagrant/bin/linux-x86_64
  basename: library.so
library unloaded
```

**Comment by iDoka** [comment]
BTW, I had issue on non-vanilla CentOS kernel version.
I use `kernel-ml` branch 4.x from repo elrepo-kernel (ELRepo.org) 
```
$ uname -a
Linux 4.15.7-1.el7.elrepo.x86_64 #1 SMP Wed Feb 28 14:38:13 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by gpakosz** [comment]
@iDoka but you didn't compile with `-D_XOPEN_SOURCE=500` right?

**Comment by iDoka** [comment]
@gpakosz I can confirm.
`-D_XOPEN_SOURCE=500` works for me on CentOS 7 with kernel 4.x
